from __future__ import annotations

import os
import shlex
import subprocess
import sys
import sysconfig
from pathlib import Path

from setuptools import Extension, setup
from setuptools.command.build_ext import build_ext

ROOT = Path(__file__).resolve().parent
os.chdir(ROOT)


def version() -> str:
    base = (ROOT / "VERSION").read_text().strip()
    local = os.environ.get("FAST_ULYSSES_LOCAL_VERSION")
    return f"{base}+{local}" if local else base


def requirements() -> list[str]:
    try:
        import torch
    except ImportError:
        raise RuntimeError(
            "Install torch first, then use: pip install -e . --no-build-isolation"
        ) from None
    major, minor = torch.__version__.split(".")[:2]
    return [f"torch=={major}.{minor}.*"]


class CMakeExtension(Extension):
    def __init__(self, name: str) -> None:
        super().__init__(name, sources=[])


class CMakeBuild(build_ext):
    def build_extension(self, ext: Extension) -> None:
        out = Path(self.get_ext_fullpath(ext.name)).resolve().parent
        build = Path(os.environ.get("FAST_ULYSSES_BUILD_DIR", ROOT / "build"))
        arch = os.environ.get("FAST_ULYSSES_CUDA_ARCH", "80;90;100;120")
        suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"
        env = os.environ.copy()
        env["TORCH_CUDA_ARCH_LIST"] = " ".join(
            f"{item[:-1]}.{item[-1]}" for item in arch.split(";") if item
        )
        build.mkdir(parents=True, exist_ok=True)
        args = [
            "cmake",
            "-S",
            str(ROOT),
            "-B",
            str(build),
            f"-DCMAKE_LIBRARY_OUTPUT_DIRECTORY={out}",
            f"-DPython_EXECUTABLE={sys.executable}",
            f"-DEXT_SUFFIX={suffix}",
            "-DCMAKE_BUILD_TYPE=Release",
            f"-DCMAKE_CUDA_ARCHITECTURES={arch}",
            f"-DFAST_ULYSSES_VERSION={version()}",
        ]
        args += shlex.split(os.environ.get("FAST_ULYSSES_CMAKE_ARGS", ""))
        subprocess.check_call(args, env=env)
        jobs = os.environ.get("CMAKE_BUILD_PARALLEL_LEVEL", "4")
        subprocess.check_call(["cmake", "--build", str(build), f"-j{jobs}"], env=env)
        self._write_build_meta(out, arch)

    @staticmethod
    def _write_build_meta(out: Path, arch: str) -> None:
        import torch

        major, minor = torch.__version__.split(".")[:2]
        values = {
            "VERSION": version(),
            "WHEEL_TAG": os.environ.get("FAST_ULYSSES_LOCAL_VERSION", ""),
            "TORCH_VERSION": torch.__version__,
            "TORCH_ABI": f"{major}.{minor}",
            "CUDA_VERSION": torch.version.cuda,
            "PYTHON_ABI": f"cp{sys.version_info.major}{sys.version_info.minor}",
            "CUDA_ARCH_LIST": arch.replace(";", ","),
            "HAS_WORK_REGISTRY": False,
        }
        (out / "_build_meta.py").write_text(
            "# Generated by setup.py.\n"
            + "".join(f"{key} = {value!r}\n" for key, value in values.items())
        )


setup(
    version=version(),
    install_requires=requirements(),
    ext_modules=[CMakeExtension("fast_ulysses._C")],
    cmdclass={"build_ext": CMakeBuild},
)
